# Model type
type : 'EMM'
# Model name
name : 'explore_vit_base'
# Checkpoint to resume
resume : ''
# Number of classes
num_classes : 1000
# Dropout rate
drop_rate : 0.0
# Drop path rate
drop_path_rate : 0.1
# Label Smoothing
label_smoothing : 0

# model hyperparameters

base_config:
  img_size: 224
  patch_size: 16
  in_chans: 3
  num_classes: 1000
  mlp_ratio: 4.
  qkv_bias: true
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.
  pos_embed: cosine
  pool: mean

vit_encoder:
  vit_type: vit_encoder
  embed_dim : 1024
  layers : 24
  heads: 16
  img_size: 224
  mask_ratio: 0.75
  patch_size : 16

vit_decoder:
  vit_type: vit_decoder
  embed_dim : 512
  layers : 8
  heads: 16
  img_size: 224
  mask_ratio: 0.75
  patch_size : 16

bert_encoder:
  bert_type: bert_encoder
  context_length : 77
  vocab_size : 49408
  transformer_width : 512
  transformer_heads : 8
  transformer_layers : 12

bert_decoder:
  bert_type: bert_decoder
  context_length : 77
  vocab_size : 49408
  transformer_width : 512
  transformer_heads : 8
  TRANSFORMER_LAYERS : 12
